name: Deploy Database Changes

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - stg
      - prod
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to Dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/deploy-database-env.yml
    with:
      environment: dev

  deploy-stg:
    name: Deploy to Stg
    if: github.event_name == 'pull_request' && github.base_ref == 'stg' && github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-database-env.yml
    with:
      environment: stg

  deploy-prod:
    name: Deploy to Prod
    if: github.event_name == 'pull_request' && github.base_ref == 'prod' && github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-database-env.yml
    with:
      environment: prod