name: Deploy Database Changes to Specific Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-database:
    name: Deploy Database Changes to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install gh-ost
        run: |
          wget https://github.com/github/gh-ost/releases/latest/download/gh-ost-binary-linux-amd64.tar.gz
          tar -xzf gh-ost-binary-linux-amd64.tar.gz
          chmod +x gh-ost
          sudo mv gh-ost /usr/local/bin/

      - name: Install doctrine/dbal
        run: composer require doctrine/dbal --no-interaction --no-dev

      - name: Check for migration changes
        id: check_migrations
        run: |
          if [[ -n "$(git diff --name-only HEAD^ HEAD -- database/migrations)" ]]; then
            echo "::set-output name=migrations_changed::true"
          else
            echo "::set-output name=migrations_changed::false"
          fi

      - name: Run gh-ost migrations (only if migrations changed)
        if: steps.check_migrations.outputs.migrations_changed == 'true'
        run: |
          chmod +x ./scripts/run-gh-ost.sh
          export DB_HOST="${{ secrets[format('DB_HOST_{0}', inputs.environment)] || '127.0.0.1' }}"
          export DB_PORT="${{ secrets[format('DB_PORT_{0}', inputs.environment)] || '3306' }}"
          export DB_USER="${{ secrets[format('DB_USER_{0}', inputs.environment)] || 'root' }}"
          export DB_PASSWORD="${{ secrets[format('DB_PASSWORD_{0}', inputs.environment)] || '' }}"
          export DB_NAME="${{ secrets[format('DB_NAME_{0}', inputs.environment)] || 'your_local_db_name' }}"
          ./scripts/run-gh-ost.sh ${{ inputs.environment }}