name: Deploy Database Changes to Specific Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-database:
    name: Deploy Database Changes to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install gh-ost
        run: |
          wget https://github.com/github/gh-ost/releases/download/v1.1.4/gh-ost-linux-amd64 -O gh-ost # Update to latest version
          chmod +x gh-ost
          sudo mv gh-ost /usr/local/bin/

      - name: Install doctrine/dbal
        run: composer require doctrine/dbal --no-interaction --no-dev

      - name: Check for migration changes
        id: check_migrations
        run: |
          if [[ -n "$(git diff --name-only HEAD^ HEAD -- database/migrations)" ]]; then
            echo "::set-output name=migrations_changed::true"
          else
            echo "::set-output name=migrations_changed::false"
          fi

      - name: Run gh-ost migrations (only if migrations changed)
        if: steps.check_migrations.outputs.migrations_changed == 'true'
        env:
          DB_HOST: ${{ secrets.DB_HOST_${{ inputs.environment }} || '127.0.0.1'}}
          DB_PORT: ${{ secrets.DB_PORT_${{ inputs.environment }} || '3306'}}
          DB_USER: ${{ secrets.DB_USER_${{ inputs.environment }} || 'root'}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_${{ inputs.environment }} || ''}}
          DB_NAME: ${{ secrets.DB_NAME_${{ inputs.environment }} || 'your_local_db_name'}}
        run: |
          chmod +x ./scripts/run-gh-ost.sh
          ./scripts/run-gh-ost.sh ${{ inputs.environment }}