name: Test MySQL Migrations

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test_migrations:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-start-period=10s
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up PHP and Composer (if using Laravel or PHP)
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, pdo_mysql
        coverage: none

    - name: Install dependencies with Composer
      run: composer install --no-interaction --prefer-dist

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping --host=localhost --user=root --password=root --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
        echo "MySQL is ready!"

    - name: Run migrations
      run: php artisan migrate --env=testing

    - name: Verify migration success
      run: |
        if php artisan migrate:status | grep -q 'No migrations'; then
          echo "No migrations have been applied, which is a failure!"
          exit 1
        else
          echo "Migrations applied successfully!"
        fi
