name: Run Migrations with gh-ost

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  migrations:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3


    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install gh-ost
      run: |
        curl -L https://github.com/github/gh-ost/releases/download/v1.1.7/gh-ost-binary-linux-amd64-20241219160321.tar.gz -o gh-ost.tar.gz
        tar -xf gh-ost.tar.gz
        chmod +x gh-ost  # Make gh-ost executable
        sudo mv gh-ost /usr/local/bin/  # Move to system PATH
        
    - name: Set Permissions for gh-ost Script
      run: chmod +x ./run-gh-ost.sh

    - name: Run gh-ost Migrations
      run: ./run-gh-ost.sh
