name: Run Migrations with gh-ost

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  migrations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install gh-ost
      run: |
        curl -L https://github.com/github/gh-ost/releases/download/v1.1.7/gh-ost-binary-linux-amd64-20241219160321.tar.gz  -o gh-ost
        chmod +x gh-ost
        sudo mv gh-ost /usr/local/bin/
        
    - name: Set Permissions for gh-ost Script
      run: chmod +x ./run-gh-ost.sh

    - name: Run gh-ost Migrations
      run: ./run-gh-ost.sh
