name: Deploy

on:
  push:
    branches:
      - dev
      - stg
      - main
  pull_request:
    types:
      closed
    branches:
      - dev
      - stg
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create .env file
        run: |
          touch .env
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_database" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root_password" >> .env

      - name: Check MySQL configuration
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot_password -e "SHOW VARIABLES LIKE 'log_bin';"
          mysql -h 127.0.0.1 -P 3306 -u root -proot_password -e "SHOW VARIABLES LIKE 'binlog_format';"
          mysql -h 127.0.0.1 -P 3306 -u root -proot_password -e "SHOW GRANTS FOR 'root'@'%';"

      - name: Run migrations (regular migrations)
        run: php artisan migrate --force --no-interaction

      - name: Show table columns
        run: mysql -h 127.0.0.1 -P 3306 -u root -proot_password test_database -e "DESCRIBE users;"

      - name: Download gh-ost binary
        run: |
          wget https://github.com/github/gh-ost/releases/download/v1.1.7/gh-ost-binary-linux-amd64-20241219160321.tar.gz
          tar -xvf gh-ost-binary-linux-amd64-20241219160321.tar.gz
          sudo mv gh-ost /usr/local/bin/ # Move to a directory in PATH
          sudo chmod +x /usr/local/bin/gh-ost

      - name: Run gh-ost migrations
        run: bash gh-ost-migrate.sh
        env:
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: test_database
            DB_USERNAME: root
            DB_PASSWORD: root_password

      - name: Show table columns after gh-ost migration
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot_password test_database -e "DESCRIBE users;"
          mysql -h 127.0.0.1 -P 3306 -u root -proot_password test_database -e "SHOW TABLES LIKE '_users_gho%';"
