name: Run Migrations with gh-ost

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  migrations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Architecture
      run: uname -a

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install Build Tools
      run: sudo apt-get update && sudo apt-get install -y git make gcc

    - name: Clone gh-ost Repository
      run: git clone https://github.com/github/gh-ost.git

    - name: Build gh-ost from Source
      run: |
        cd gh-ost
        make build
        sudo mv bin/gh-ost /usr/local/bin/

    - name: Verify gh-ost Binary
      run: file /usr/local/bin/gh-ost

    - name: Set Permissions for gh-ost Script
      run: chmod +x ./run-gh-ost.sh

    - name: Run gh-ost Migrations
      run: ./run-gh-ost.sh

    - name: Run Standard Laravel Migrations
      run: php artisan migrate --force
